version: '3.8'
services:
  mariadb:
    container_name: 'docker-mariadb-go-restapi-gin'
    image: mariadb:latest
    ports:
    - '3306:3306'
    environment:
    - MYSQL_ROOT_PASSWORD=root
    - MYSQL_DATABASE=db_go_restapi_gin

  phpmyadmin:
    image: phpmyadmin:latest
    ports:
    - '8000:80'
    environment:
    - PMA_ARBITRARY=1